openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of my contacts app
tags:
  - name: Contacts
    description: Operation about Contacts
  - name: Auth
    description: Auth operation

servers:
  - url: http://localhost:3000
  - url: https://nodejs-hw-mongodb-tqks.onrender.com
paths:
  /contacts/{id}:
    get:
      $ref: ../src/swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../src/swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../src/swagger/paths/contacts/{id}/delete.yaml
  /contacts:
    get:
      $ref: ../src/swagger/paths/contacts/get.yaml
    post:
      $ref: ../src/swagger/paths/contacts/post.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
